"""recreate upload_files table

Revision ID: 351454506ccb
Revises: 
Create Date: 2025-08-02 02:31:22.148090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351454506ccb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_files',
    sa.Column('id', sa.String(length=255), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('storage_type', sa.String(length=255), nullable=False, comment='Type of storage used for the file, local, cloud etc.'),
    sa.Column('key', sa.String(length=255), nullable=False, comment='File path in storage'),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('used_by', sa.String(length=255), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('hash', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='upload_file_pkey')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_files')
    # ### end Alembic commands ###
